name: Deploy my book

on:
  push:
    branches:
      - master  # 只在master上push触发部署
    paths-ignore:   # 下列文件的变更不触发部署，可以自行添加
      - README.md

jobs:
  deploy:

    runs-on: ubuntu-latest   # 使用ubuntu系统镜像运行自动化脚本

    steps:  # 自动化步骤
      - uses: actions/checkout@v2   # 第一步，下载代码仓库

      - name: Setup Hugo  # 第二步，安装 hugo
        uses: peaceiris/actions-hugo@v2
        with: 
          hugo-version: '0.105.0'

      - name: Build  # 第三步，编译 hugo
        run: |
          cd ./book
          hugo -D --minify
          
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # This is the branch where the docs are deployed to
          branch: master
          folder: book/public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }} # 这里的 ACTIONS_DEPLOY_KEY 则是上面设置 Private Key的变量名
          external_repository: ivylet/ivylet.github.io # Pages 远程仓库 
          publish_dir: "./book/public"
          keep_files: false # remove existing files
          publish_branch: master  # deploying branch
          commit_message: ${{ github.event.head_commit.message }}



    # - name: Deploy to Server  # 第四步，rsync推文件
    #   uses: AEnterprise/rsync-deploy@v1.0  # 使用别人包装好的步骤镜像
    #   env:
    #     DEPLOY_KEY: ${{ secrets.DEPLOY_KEYS }}   # 引用配置，SSH私钥
    #     ARGS: -avz --delete --exclude='*.pyc'   # rsync参数，排除.pyc文件
    #     SERVER_PORT: '22'  # SSH端口
    #     FOLDER: ./book/public/* #推送的文件夹，路径相对于代码仓库的根目录
    #     SERVER_IP: ${{ secrets.SSH_HOST }}  # 引用配置，服务器的host名（IP或者域名domain.com）
    #     USERNAME: ${{ secrets.SSH_USERNAME }}  # 引用配置，服务器登录名
    #     SERVER_DESTINATION: /www/wwwroot/books/leetcode/   # 部署到目标文件夹